config/routes.rb
Rails.application.routes.draw do

  # authorization with auth0
  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'

  get '/logout' => 'logout#logout'

  resources :alumnis
  root to: 'regions#index'
  get '/regions', to: 'regions#index'
  get '/regions/:id', to: 'regions#show'

  get '/healthz', to: proc { [200, {}, ['']] }
end

app/models/alumni.rb
class Alumni < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample_data.rb
class SampleData < ApplicationRecord
end

app/controllers/alumnis_controller.rb
class AlumnisController < ApplicationController
  include Secured

  before_action :set_alumni, only: [:show, :edit, :update, :destroy]

  # GET /alumnis
  # GET /alumnis.json
  def index
    @alumnis = Alumni.all
  end

  # GET /alumnis/1
  # GET /alumnis/1.json
  def show
  end

  # GET /alumnis/new
  def new
    @alumni = Alumni.new
  end

  # GET /alumnis/1/edit
  def edit
  end

  # POST /alumnis
  # POST /alumnis.json
  def create
    @alumni = Alumni.new(alumni_params)

    respond_to do |format|
      if @alumni.save
        format.html { redirect_to @alumni, notice: 'Alumni was successfully created.' }
        format.json { render :show, status: :created, location: @alumni }
      else
        format.html { render :new }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnis/1
  # PATCH/PUT /alumnis/1.json
  def update
    respond_to do |format|
      if @alumni.update(alumni_params)
        format.html { redirect_to @alumni, notice: 'Alumni was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumni }
      else
        format.html { render :edit }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnis/1
  # DELETE /alumnis/1.json
  def destroy
    @alumni.destroy
    respond_to do |format|
      format.html { redirect_to alumnis_url, notice: 'Alumni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumni
      @alumni = Alumni.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alumni_params
      params.require(:alumni).permit(:first, :last, :linkedin_profile, :graduation_year, :tags)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # OmniAuth places the User Profile information (retrieved by omniauth-auth0) in request.env['omniauth.auth'].
    # In this tutorial, you will store that info in the session, under 'userinfo'.
    # If the id_token is needed, you can get it from session[:userinfo]['credentials']['id_token'].
    # Refer to https://github.com/auth0/omniauth-auth0#auth-hash for complete information on 'omniauth.auth' contents.
    session[:userinfo] = request.env['omniauth.auth']

    redirect_to '/alumnis'
  end

  # if user authentication fails on the provider side OmniAuth will redirect to /auth/failure,
  # passing the error message in the 'message' request param.
  def failure
    @error_msg = request.params['message']
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  include LogoutHelper
  def logout
    reset_session
    redirect_to logout_url.to_s
  end
end

app/controllers/regions_controller.rb
# frozen_string_literal: true

# RegionsController handles selecting a region and rolling the dice
class RegionsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/alumnis_helper.rb
module AlumnisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
  def logout_url
    domain = Rails.application.credentials.auth0_domain
    client_id = Rails.application.credentials.auth0_client_id
    request_params = {
      returnTo: root_url,
      client_id: client_id
    }

    URI::HTTPS.build(host: domain, path: '/v2/logout', query: to_query(request_params))
  end

  private

  def to_query(hash)
    hash.map { |k, v| "#{k}=#{CGI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
  end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/alumnis/_form.html.erb
<%= form_with(model: alumni, local: true) do |form| %>
  <% if alumni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumni.errors.count, "error") %> prohibited this alumni from being saved:</h2>

      <ul>
        <% alumni.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :linkedin_profile %>
    <%= form.text_field :linkedin_profile %>
  </div>

  <div class="field">
    <%= form.label :graduation_year %>
    <%= form.text_field :graduation_year %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alumnis/edit.html.erb
<h1>Editing Alumni</h1>

<%= render 'form', alumni: @alumni %>

<%= link_to 'Show', @alumni %> |
<%= link_to 'Back', alumnis_path %>

app/views/alumnis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnis</h1>

<div><p>Login Information</p>
  <p><%= session[:userinfo].inspect %></p>
</div>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Linkedin profile</th>
      <th>Graduation year</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnis.each do |alumni| %>
      <tr>
        <td><%= alumni.first %></td>
        <td><%= alumni.last %></td>
        <td><%= alumni.linkedin_profile %></td>
        <td><%= alumni.graduation_year %></td>
        <td><%= alumni.tags %></td>
        <td><%= link_to 'Show', alumni %></td>
        <td><%= link_to 'Edit', edit_alumni_path(alumni) %></td>
        <td><%= link_to 'Destroy', alumni, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumni', new_alumni_path %>

app/views/alumnis/new.html.erb
<h1>New Alumni</h1>

<%= render 'form', alumni: @alumni %>

<%= link_to 'Back', alumnis_path %>

app/views/alumnis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @alumni.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @alumni.last %>
</p>

<p>
  <strong>Linkedin profile:</strong>
  <%= @alumni.linkedin_profile %>
</p>

<p>
  <strong>Graduation year:</strong>
  <%= @alumni.graduation_year %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @alumni.tags %>
</p>

<%= link_to 'Edit', edit_alumni_path(@alumni) %> |
<%= link_to 'Back', alumnis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleTransect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'stylesheets' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if session[:userinfo] %>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'logout' %>"><a id="qsLogoutBtn" href="/logout">Logout</a></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/regions/index.html.erb
<!--
<img src="https://cdn.auth0.com/styleguide/1.0.0/img/badge.svg">
<h1>Auth0 Login:</h1>
<%= button_to 'Login', 'auth/auth0', method: :post %>
-->

<div id="outer-box">
  <%= image_pack_tag "Wondrous Wetland.png" %>
  <div id="outer-container" data-controller="sample">
  <%
    (1..14).each do |y|
      (1..14).each do |x|
        y_class = "y-box-#{y}"
        x_class = "x-box-#{x}"
        y_oriented_number = y + ((x-1) * 14)
        x_oriented_number = ((y-1) * 14) + x

        plot_number = x_oriented_number
      %>
    <div class="<%= y_class %> <%= x_class %> inner-box" id="plot-<%= plot_number %>">
      <a href="/regions/<%= plot_number %>" data-turbolinks-persist-scroll="true"><p>#<%= plot_number %></p></a>
    </div>
    <%
      end
  end %>
  </div>
</div>

app/views/regions/show.html.erb
<div id="outer-box">
  <%= image_pack_tag "Wondrous Wetland.png" %>
  <div id="outer-container">
  <div id="location-reminder">
    <p>Plot&nbsp;#:&nbsp;<%= params[:id] %></p>
  </div>
  <%
    (1..14).each do |y|
      (1..14).each do |x|
        y_class = "y-box-#{y}"
        x_class = "x-box-#{x}"
        y_oriented_number = y + ((x-1) * 14)
        x_oriented_number = ((y-1) * 14) + x

        plot_number = x_oriented_number
      %>
      <% if plot_number.to_s == params[:id] %>
        <div class="<%= y_class %> <%= x_class %> selected-box" id="plot-<%= plot_number %>">
          <p>&nbsp;<%= SampleData.find(params[:id]).sample_count %></p>
        </div>
      <% else %>
        <div class="<%= y_class %> <%= x_class %> inner-box" id="plot-<%= plot_number %>">
          <a href="/regions/<%= plot_number %>" data-turbolinks-persist-scroll="true"><p>#<%= plot_number %></p></a>
        </div>
      <% end %>
    <%
      end
  end %>
  </div>
</div>